[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "wallfetch"
version = "0.1.0"
description = "A CLI tool for downloading wallpapers from Wallhaven.cc"
readme = "README.md"
requires-python = ">=3.11"

authors = [{ name = "Aditya1770" }]

dependencies = [
    "requests",
    "rich",
    "tomli-w",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Graphics",
]

[project.urls]
Homepage = "https://github.com/Aditya1770/wallfetch"
Repository = "https://github.com/Aditya1770/wallfetch"
Issues = "https://github.com/Aditya1770/wallfetch/issues"

[project.scripts]
wallfetch = "wallfetch.cli:main"


[tool.setuptools.packages.find]
where = ["src"]
